services:

  prediction-service:
    ports: []

  prediction-service-1:
    build:
      context: .
      dockerfile: prediction-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - model-storage:/app/storage

  prediction-service-2:
    build:
      context: .
      dockerfile: prediction-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - model-storage:/app/storage

  prediction-service-3:
    build:
      context: .
      dockerfile: prediction-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - model-storage:/app/storage

  nginx-lb:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - prediction-service
      - prediction-service-1
      - prediction-service-2
      - prediction-service-3
