global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ml-cloud-services"
    scheme: https
    static_configs:
      - targets: 
        # Your live Prediction Service
        - "ml-prediction-service-m7xo.onrender.com"
        
        # You can uncomment and add your other live Render URLs here 
        # once you want to monitor them as well!
        # - "ml-auth-service-xxxx.onrender.com"
        # - "ml-model-service-xxxx.onrender.com"