global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ml-inference-platform'
    metrics_path: '/metrics'
    static_configs:
      - targets: 
        - 'auth-service:8000'
        - 'model-service:8000'
        - 'prediction-service:8000'
        - 'prediction-service-1:8000'
        - 'prediction-service-2:8000'
        - 'prediction-service-3:8000'