events {}

http {

    upstream prediction_backend {
        least_conn;

        server prediction-service:8000;
        server prediction-service-1:8000;
        server prediction-service-2:8000;
        server prediction-service-3:8000;
    }

    server {

        listen 80;

        location /api/v1/predictions/ {

            proxy_pass http://prediction_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        }

    }

}